version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    # Image with ICU plugin enabled
    #image: adeo-docker-adeo-opus-release.jfrog.io/opus-search-elasticsearch-with-icu:7.6.1
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - http.port=9201
      - TAKE_FILE_OWNERSHIP=true
    ports:
      - 9201:9201
    volumes:
      - ../../data/elasticsearch:/usr/share/elasticsearch/data

  opensearch-node1:
    image: gsingers/opensearch-learning-to-rank:1.2.3
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - http.max_content_length=1000mb
      - "OPENSEARCH_JAVA_OPTS=-Xms2G -Xmx2G"

    ports:
      - 9200:9200

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
