#### WEEK 1

# - pipeline.id: product_indexing
#   path.config: "/workspace/search_with_machine_learning_course/logstash/week1/config/index-bbuy-products.logstash"
# - pipeline.id: queries_indexing
#   path.config: "/workspace/search_with_machine_learning_course/logstash/week1/config/index-bbuy-queries.logstash"

#### WEEK 2

- pipeline.id: product_indexing
  path.config: "/workspace/search_with_machine_learning_course/logstash/week2/config/index-bbuy-products.logstash"
- pipeline.id: queries_indexing
  path.config: "/workspace/search_with_machine_learning_course/logstash/week2/config/index-bbuy-queries.logstash"